apiVersion: 1

datasources:
  - name: InfluxDB-WFR
    type: influxdb
    access: proxy
    url: ${INFLUXDB_URL:-http://influxdb3:8181}
    database: WFR25
    jsonData:
      version: Flux
      organization: WFR
      defaultBucket: WFR25
      tlsSkipVerify: true
      httpMode: POST
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
    editable: true
    uid: influxdb-wfr-v2
